[package]
name = "dioxus-desktop-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
dioxus-std = { version = "0.4.0", features = ["clipboard", "utils"] }
